#pragma once

/// Image widget — displays a pre-converted pixel array.
/// Image data is generated by `lumen-tools image` from PNG files.
/// Supports RGB565 (for SPI displays) and ARGB8888 (for framebuffer displays).

#include "lumen/core/pixel_format.hpp"
#include "lumen/ui/widget.hpp"

namespace lumen::ui {

/// Displays a static image from a compile-time pixel array.
class Image : public Widget
{
  public:
	Image() = default;

	/// Set the image data (RGB565 pixel array).
	void set_image_rgb565(const uint16_t* data, uint16_t img_w, uint16_t img_h)
	{
		data_rgb565_ = data;
		data_argb_	 = nullptr;
		img_w_		 = img_w;
		img_h_		 = img_h;
		invalidate();
	}

	/// Set the image data (ARGB8888 pixel array).
	void set_image_argb(const uint32_t* data, uint16_t img_w, uint16_t img_h)
	{
		data_argb_	 = data;
		data_rgb565_ = nullptr;
		img_w_		 = img_w;
		img_h_		 = img_h;
		invalidate();
	}

	void draw(gfx::Canvas<ActivePixFmt>& canvas) override
	{
		if (img_w_ == 0 || img_h_ == 0)
			return;

		// Calculate position (centered in bounds)
		int16_t off_x = bounds().x + (bounds().w - img_w_) / 2;
		int16_t off_y = bounds().y + (bounds().h - img_h_) / 2;

		if (data_rgb565_ != nullptr)
		{
			for (uint16_t row = 0; row < img_h_; ++row)
			{
				for (uint16_t col = 0; col < img_w_; ++col)
				{
					uint16_t px = data_rgb565_[row * img_w_ + col];
					// Convert RGB565 to Color then to canvas pixel
					Color c = Color::from_rgb565(px);
					canvas.put_pixel(static_cast<int16_t>(off_x + col),
									 static_cast<int16_t>(off_y + row),
									 gfx::Canvas<ActivePixFmt>::to_pixel_static(c));
				}
			}
		}
		else if (data_argb_ != nullptr)
		{
			for (uint16_t row = 0; row < img_h_; ++row)
			{
				for (uint16_t col = 0; col < img_w_; ++col)
				{
					uint32_t px = data_argb_[row * img_w_ + col];
					uint8_t r	= static_cast<uint8_t>((px >> 16) & 0xFF);
					uint8_t g	= static_cast<uint8_t>((px >> 8) & 0xFF);
					uint8_t b	= static_cast<uint8_t>(px & 0xFF);
					Color c		= Color::rgb(r, g, b);
					canvas.put_pixel(static_cast<int16_t>(off_x + col),
									 static_cast<int16_t>(off_y + row),
									 gfx::Canvas<ActivePixFmt>::to_pixel_static(c));
				}
			}
		}
	}

  private:
	const uint16_t* data_rgb565_ = nullptr;
	const uint32_t* data_argb_	 = nullptr;
	uint16_t img_w_				 = 0;
	uint16_t img_h_				 = 0;
};

} // namespace lumen::ui
